# Generated by Django 5.1.6 on 2025-02-27 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('victory', models.PositiveIntegerField(default=0)),
                ('defeat', models.PositiveIntegerField(default=0)),
                ('online', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(related_name='friends_of', through='core.Friendship', to='core.player')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('En cours', 'En Cours'), ('Pause', 'Pause'), ('Terminée', 'Terminee')], default='En cours', max_length=10)),
                ('type', models.CharField(choices=[('IA', 'Ia'), ('Privée', 'Privee'), ('Public', 'Public'), ('Tournois', 'Tournament')], default='Privée', max_length=10)),
                ('private_code', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player_1', to='core.player')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player_2', to='core.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_player_1', models.PositiveIntegerField(default=0)),
                ('score_player_2', models.PositiveIntegerField(default=0)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('En cours', 'En Cours'), ('Pause', 'Pause'), ('Terminée', 'Terminee')], default='En cours', max_length=10)),
                ('ball_position', models.JSONField(default=dict)),
                ('paddle_position', models.JSONField(default=dict)),
                ('ball_dx', models.IntegerField(default=1)),
                ('ball_dy', models.IntegerField(default=0)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='core.match')),
                ('player_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player_1', to='core.player')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player_2', to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='friendship',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests', to='core.player'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to='core.player'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('En cours', 'En Cours'), ('Pause', 'Pause'), ('Terminée', 'Terminee')], default='En cours', max_length=10)),
                ('players', models.ManyToManyField(related_name='tournaments', to='core.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_won', to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.tournament'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_players', to='core.player')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='core.player')),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
