# Generated by Django 5.1.5 on 2025-03-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
