# Generated by Django 5.1.7 on 2025-03-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_description_player_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('player_1', 'player_2')},
        ),
    ]
